
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Precious
 */
public class Homepage extends javax.swing.JFrame {

    String studentStrand;
    String studentSkill;
    String studentLocation;
    String username;
    private String skill;
    private String strand;

    public Homepage(String strand, String skill, String location, String user) {
        initComponents();
        setLocationRelativeTo(null);
        
        // Store user data
        studentStrand = strand;
        studentSkill = skill;
        studentLocation = location;
        username = user;
        
        // Load job recommendations
        loadRecommendedJobs();
    }

    public Homepage() {
        initComponents();
    }

    // Your existing loadRecommendedJobs() method
   public void loadRecommendedJobs() {
     try {
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3307/kita_system", "root", "");
        
        // Simpler query - just match by location and strand
        String sql = "SELECT * FROM jobs WHERE location=? AND strand=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, studentLocation);
        pst.setString(2, studentStrand);
        
        ResultSet rs = pst.executeQuery();
        
        jPanel4.removeAll();
        
        int jobCount = 0;
        while (rs.next()) {
            jobCount++;
            
            JPanel card = createJobCard(
                rs.getString("job_title"),
                rs.getString("company"),
                rs.getString("strand"),
                rs.getString("skill"),
                rs.getString("location")
            );
            
            jPanel4.add(card);
        }
        
        if (jobCount == 0) {
            JLabel noJobs = new JLabel("🔍 No jobs found for " + studentStrand + " strand in " + studentLocation);
            noJobs.setFont(new java.awt.Font("Segoe UI", 1, 14));
            jPanel4.add(noJobs);
        }
        
        jPanel4.revalidate();
        jPanel4.repaint();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }

}

    // Your existing createJobCard method
   public JPanel createJobCard(String title, String company, String strand, String skill, String location) {
    // Create card panel
    JPanel card = new JPanel();
    card.setPreferredSize(new java.awt.Dimension(280, 180));
    card.setBackground(java.awt.Color.white);
    card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 2),
        javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
    ));
    card.setLayout(new java.awt.GridLayout(6, 1, 5, 5));
    
    // Create labels
    JLabel jobTitle = new JLabel("💼 " + title);
    jobTitle.setFont(new java.awt.Font("Segoe UI", 1, 14));
    jobTitle.setForeground(new java.awt.Color(0, 102, 0));
    
    JLabel jobCompany = new JLabel("🏢 " + company);
    JLabel jobStrand = new JLabel("🎓 Strand: " + strand);
    JLabel jobSkill = new JLabel("⚙️ Skill: " + skill);
    JLabel jobLocation = new JLabel("📍 " + location);
    JLabel applyBtn = new JLabel("<html><b style='color: green;'>[APPLY NOW]</b></html>");
    
    // Add labels to card
    card.add(jobTitle);
    card.add(jobCompany);
    card.add(jobStrand);
    card.add(jobSkill);
    card.add(jobLocation);
    card.add(applyBtn);
    
    return card;

    }
    
    // ... rest of your code ...


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChatGPT Image Mar 14, 2026, 12_37_37 PM (1).png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setText("PROFILE");

        jButton2.setText("LOGOUT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 724, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
